language: ruby
os: linux
rvm:
 - 2.6.5
cache:
  bundler: true
  # directories:
  #   - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
before_install:
  - gem install bundler
gemfile: Gemfile
script:
      JEKYLL_ENV=production bundle exec jekyll build; 
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - source
    - develop
    
sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $api  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local_dir: _site
  # repo: luispuerto/luispuerto.net # in case I wanted to build my page in other repo
  target-branch: master
  on:
    branch: source



